sudo: required
language: node_js
node_js:
    - stable
services:
    - xvfb
addons:
  chrome: stable
cache:
    directories:
        - node_modules
notifications:
    email: false
branches:
    only:
        - master
before_script:
  - export DISPLAY=:99.0
script:
  - npm run lint
  - npm test -- --single-run
